import Head from "next/head";
import { Inter } from "next/font/google";
import style from "../styles/index.module.css";

// Função assíncrona que será chamada pelo Next.js para carregar os dados do servidor
export async function getServerSideProps() {
  const resp = await fetch("http://localhost:3000/api/valoresController");
  const valores = await resp.json();

  
  
  return {
    props: {
      contas: valores
    },
  };
}

const inter = Inter({ subsets: ["latin"] });

export default function Home({ contas }) {
  return (
    <>
      <Head>
        <title>Débitos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.main}>
        <table>
          <thead>
            <tr>
              <th>Valor</th>
              <th>Nome</th>
              <th>Data</th>
            </tr>
          </thead>
          <tbody>
            {contas.map((elemento) => (
              <tr key={elemento.id}>
                <td>{elemento.valor}</td>
                <td>{elemento.nome}</td>
                <td>{elemento.data}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}
